name: Padavan (Mi R3G)

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/padavan_mi-r3g.yml'
      - 'padavan/common.sh'
      - 'padavan/mi-r3g.sh'
  schedule:
    - cron: 0 16 * * 5

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Environment Initialization
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
      
      - name: Fetch Padavan Source
        run: |
          git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          mkdir -p /opt/images/

      - name: Run Customization
        run: |
          chmod +x padavan/*.sh
          ./padavan/common.sh MI-R3G
          ./padavan/mi-r3g.sh

      - name: Build Firmware
        working-directory: /opt/rt-n56u/trunk
        run: |
          sudo ./clear_tree
          sudo ./build_firmware_modify MI-R3G 0
          sudo mv -f images/*.trx /opt/images/
          echo "::set-output name=status::success"
          echo "::set-env name=BUILD_DATE::$(date +"%y%m%d.%H%M")"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BUILD_DATE }}
          release_name: Padavan_Mi-R3G_${{ env.BUILD_DATE }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /opt/images/MI-R3G_3.4.3.9-099.trx
          asset_name: Padavan_Mi-R3G_${{ env.BUILD_DATE }}.trx
          asset_content_type: application/octet-stream